---
- name: Install systemd-timesyncd
  package:
    name:
      - systemd-timesyncd
    state: installed
  when:
    - ansible_os_family == 'RedHat'

- name: Set NTP server in /etc/systemd/timesyncd.conf
  template:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart systemd-timesyncd

- name: disable ntpd and chronyd related services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - ntpdate
    - ntpd
    - chronyd
  ignore_errors: yes

- name: Manage systemd-timesyncd service to be enabled and running
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - systemd-timesyncd.service
  tags:
    - molecule-idempotence-notest
