---
- name: Set NTP server in /etc/systemd/timesyncd.conf
  template:
    src:   timesyncd.conf
    dest:  /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode:  '0644'

- name: disable ntpd and chronyd related services
  service:
    name:    "{{ item }}"
    state:   stopped
    enabled: no
  with_items:
    - ntpdate
    - ntpd
  ignore_errors: yes

- name: Manage systemd-timesyncd service to be enabled and running
  service:
    name:    "{{ item }}"
    state:   started
    enabled: yes
  with_items:
    - systemd-timesyncd.service
    - systemd-time-wait-sync.service
