---
- name: Prepare
  hosts: all
  tasks:
    - name: install dbus
      apt:
        name: dbus
        state: present
        update_cache: yes
      when:
        - ansible_facts['os_family'] == "Debian"
